//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pile.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropDownValue
    {
        public int DropDownValueId { get; set; }
        public string DropDownName { get; set; }
        public string DropDownValue1 { get; set; }
        public string DropDownText { get; set; }
        public Nullable<bool> Display { get; set; }
    }
}
