//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pile.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAddress
    {
        public long Id { get; set; }
        public int CustomerId { get; set; }
        public bool IsPrimary { get; set; }
        public string Email { get; set; }
        public bool ServiceEmails { get; set; }
        public string Info { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
