//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pile.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int ServiceDetailId { get; set; }
        public int CustomerId { get; set; }
        public int Day { get; set; }
        public int Crew { get; set; }
        public int ServiceId { get; set; }
        public decimal Price { get; set; }
        public decimal QtyPrice { get; set; }
        public decimal Discount { get; set; }
        public Nullable<bool> RequestDiscount { get; set; }
        public Nullable<decimal> EstNum { get; set; }
        public decimal AdditAmount { get; set; }
        public Nullable<int> NumDogs { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> EmpPayAdj { get; set; }
        public Nullable<decimal> AdditDogs { get; set; }
        public decimal InvoiceAmount { get; set; }
        public bool NonTaxable { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<System.DateTime> StartServiceDate { get; set; }
        public Nullable<System.DateTime> LastRouteDate { get; set; }
        public short CountDown { get; set; }
        public Nullable<int> ServicePackageId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
