//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pile.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceDetails = new HashSet<ServiceDetail>();
        }
    
        public int ServiceId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> QtyPrice { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> Active { get; set; }
        public bool AutoPop { get; set; }
        public bool ExcludeEmpPay { get; set; }
        public Nullable<decimal> AdditDogs { get; set; }
        public decimal FlatEmpPayAmt { get; set; }
        public decimal QtyFlatPayAmt { get; set; }
        public int Freq { get; set; }
        public Nullable<short> CountDown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
        public virtual Frequency Frequency { get; set; }
    }
}
