//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pile.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistory
    {
        public int Id { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public int EmployeeId { get; set; }
        public int CustomerId { get; set; }
        public string Description { get; set; }
        public bool Complaint { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
