//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pile.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceDay()
        {
            this.ServiceDetails = new HashSet<ServiceDetail>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int Day { get; set; }
        public int CrewId { get; set; }
        public int NumDogs { get; set; }
        public decimal EstNum { get; set; }
        public bool NonTaxable { get; set; }
    
        public virtual Crew Crew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
    }
}
