//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pile.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int AssignToEmpId { get; set; }
        public int Priority { get; set; }
        public int ToDoTypeId { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool Completed { get; set; }
        public string Notes { get; set; }
        public int CreatedByEmpId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CompletedByEmpId { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ToDoType ToDoType { get; set; }
    }
}
